=pod

=encoding UTF-8

=head1 NAME

URI::Fast - A fast URI parser

=head1 VERSION

version 0.01

=head1 SYNOPSIS

  use URI::Fast qw(uri);

  my $uri = uri 'http://www.example.com/some/path?a=b&c=d';

  if ($uri->scheme eq 'http') {
    my @path = $uri->split_path;
    my $a = $uri->param('a');
    my $b = $uri->param('b');
  }

=head1 DESCRIPTION

L<URI> is an excellent module. It is battle-tested, robust, and at this point
handles nearly every edge case imaginable. It is often the case, however, that
one just needs to grab the path string out of a URL. Or validate some query
parameters. Et cetera. In those cases, L<URI> may seem like overkill and may,
in fact, be much slower than a simpler solution, like L<URI::Split>.
Unfortunately, L<URI::Split> is so bare bones that it does not even parse the
authorization section or provide an object that can be easily modified.

C<URI::Fast> aims to bridge the gap between the two extremes. It provides fast
parsing without many of the frills of L<URI> while at the same time providing
I<slightly> more than L<URI::Split> by returning an object with methods to
access portiosn of the URI.

=head1 EXPORTED SUBROUTINES

=head2 uri

Accepts a string, minimally parses it (using L<URI::Split>), and returns a
L<URI::Fast> object.

When initially created, only the scheme, authorization section, path, query
string, and fragment are split out. Breaking these down further is done as
needed.

=head2 fast_URI

Returns an instance of L<URI> or the appropriate subclass, if available. It
does this faster than the URI constructor does by skipping some of the edge
cases it guards against, such as unwrapping, stringifying refs, and trimming
leading and trailing spaces.

=head1 ATTRIBUTES

=head2 scheme

Defaults to C<file> if not present in the uri string.

=head2 auth

The authorization section is composed of any the username, password, host name,
and port number.

  someone:secret@hostname.com:1234

Accessing the following attributes may incur a small amount of extra overhead
the first time they are called and the auth string is parsed.

=over

=item usr

=item pwd

=item host

=item port

=back

=head2 path

The entire path string. Trailing slashes are removed.

=over

=item split_path

Returns the path as an array ref of each segment, split by C</>. The separator
(forward slash) is excluded from the strings.

=back

=head2 query

The complete query string. Does not include the leading C<?>.

=over

=item param

Gets a parameter value. The first time this is called, it incurs the overhead
of parsing and decoding the query string.

If the key appears more than once in the query string, the value returned will
be an array ref of each of its values.

=back

=head2 frag

The fragment section of the URI, excluding the leading C<#>.

=head1 AUTHOR

Jeff Ober <sysread@fastmail.fm>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2018 by Jeff Ober.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
