name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'

        perl:
          - 'latest'

    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: perl -V
        run:  perl -V

      - name: Build makefile
        run:  perl Makefile.PL

      - name: Install dependencies
        run:  cpanm -nq --installdeps .

      - name: Run tests
        run:  make test
