name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING:      1
      AUTOMATED_TESTING:   1
      RELEASE_TESTING:     1
      PERL_ANYEVENT_MODEL: Perl

    strategy:
      fail-fast: false

      matrix:
        os:
          - 'ubuntu-latest'
          #- 'macos-latest'
          - 'windows-latest'

        perl:
          - 'latest'
          #- '5.32'
          #- '5.30'
          #- '5.28'
          #- '5.26'
          #- '5.24'
          #- '5.22'
          #- '5.20'
          - '5.18'

    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: perl -V
        run:  perl -V

      - name: Update ExtUtils::MakeMaker
        run:  cpanm -nq --reinstall ExtUtils::MakeMaker

      - name: Build makefile
        run:  perl Makefile.PL

      - name: Install dependencies
        run:  cpanm -n --installdeps .

      - name: Run tests
        run:  make test
